---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: tf-controller
  namespace: flux-system
spec:
  interval: 1h
  url: https://flux-iac.github.io/tf-controller
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tf-controller
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: tf-controller
      version: ">=0.16.0"
      sourceRef:
        kind: HelmRepository
        name: tf-controller
      interval: 1m
  values:
    runner:
      serviceAccount:
        allowedNamespaces:
        - flux-system
